<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>AccountingSystem.Service</RootNamespace>
    <AssemblyName>AccountingSystem.Service</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\AccountingSystem.Data\AccountingSystem.Data.csproj" />
    <ProjectReference Include="..\..\AccountingSystem.Entity\AccountingSystem.Entity.csproj" />
  </ItemGroup>

</Project>
