// <auto-generated />
namespace AccountingSystem.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddLanguage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddLanguage));
        
        string IMigrationMetadata.Id
        {
            get { return "201608131410283_AddLanguage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
